#!/usr/bin/env bash
# -*- coding: utf8 -*-
# ex: set fdm=marker
echo -e "\\e[33m :: INSTALLING MAKE SKELETON SCRIPTS :: \\e[39m"
echo -e "\\e[32m   you may be asked for your root password \\e[39m"
echo -e "\\e[34m :: SYMLINKING \\e[34mbin/*\\e[39m SCRIPTS TO \\e[34m/usr/local/bin\\e[39m :: \\e[39m"
if [ -f "/usr/local/bin" ]; then
  echo -e "\\e[36m file is already linked \\e[39m"
  echo -e "\\e[32m overwriting \\e[39m"
  if [ -w "/usr/local/bin" ]; then
    rm /usr/local/bin/ms
  else
    sudo rm /usr/local/bin/ms
  fi
fi
echo -e "\\e[33msymlinking\\e[39m"
if [ -w "/usr/local/bin" ]; then
  ln -s bin/ms /usr/local/bin/ms
else
  sudo ln -s bin/ms /usr/local/bin/ms
fi
